export type LatexCommand = {
  label: string;
  detail?: string;
  info?: string;
};

export const LATEX_COMMANDS: LatexCommand[] = [
  // Document structure
  { label: "\\documentclass", detail: "class", info: "Document class declaration" },
  { label: "\\usepackage", detail: "package", info: "Import a LaTeX package" },
  { label: "\\RequirePackage", detail: "package", info: "Require a LaTeX package (for class files)" },
  { label: "\\begin", detail: "env", info: "Begin an environment" },
  { label: "\\end", detail: "env", info: "End an environment" },
  { label: "\\title", detail: "meta" },
  { label: "\\author", detail: "meta" },
  { label: "\\date", detail: "meta" },
  { label: "\\maketitle", detail: "meta" },
  { label: "\\tableofcontents", detail: "meta" },
  { label: "\\listoffigures", detail: "meta" },
  { label: "\\listoftables", detail: "meta" },
  { label: "\\appendix", detail: "structure" },
  { label: "\\frontmatter", detail: "book" },
  { label: "\\mainmatter", detail: "book" },
  { label: "\\backmatter", detail: "book" },

  // Sections
  { label: "\\part", detail: "section" },
  { label: "\\chapter", detail: "section" },
  { label: "\\section", detail: "section" },
  { label: "\\subsection", detail: "section" },
  { label: "\\subsubsection", detail: "section" },
  { label: "\\paragraph", detail: "section" },
  { label: "\\subparagraph", detail: "section" },

  // Formatting
  { label: "\\textbf", detail: "format", info: "Bold text" },
  { label: "\\textit", detail: "format", info: "Italic text" },
  { label: "\\emph", detail: "format", info: "Emphasized text" },
  { label: "\\textsc", detail: "format", info: "Small caps" },
  { label: "\\texttt", detail: "format", info: "Monospace text" },
  { label: "\\textsf", detail: "format", info: "Sans-serif text" },
  { label: "\\underline", detail: "format" },
  { label: "\\textsuperscript", detail: "format" },
  { label: "\\textsubscript", detail: "format" },

  // Refs / labels
  { label: "\\label", detail: "ref", info: "Define a label for cross-reference" },
  { label: "\\ref", detail: "ref", info: "Cross-reference a label" },
  { label: "\\eqref", detail: "ref", info: "Reference equation (amsmath)" },
  { label: "\\pageref", detail: "ref" },
  { label: "\\autoref", detail: "ref", info: "Smart cross-reference (hyperref)" },
  { label: "\\nameref", detail: "ref" },
  { label: "\\hyperref", detail: "ref" },
  { label: "\\cite", detail: "cite", info: "Cite a bibliography entry" },
  { label: "\\citep", detail: "cite", info: "Parenthetical citation (natbib/biblatex)" },
  { label: "\\citet", detail: "cite", info: "Textual citation (natbib/biblatex)" },
  { label: "\\citeauthor", detail: "cite" },
  { label: "\\citeyear", detail: "cite" },
  { label: "\\nocite", detail: "cite" },
  { label: "\\bibliography", detail: "bib" },
  { label: "\\bibliographystyle", detail: "bib" },
  { label: "\\addbibresource", detail: "bib", info: "biblatex: add .bib file" },
  { label: "\\printbibliography", detail: "bib", info: "biblatex: render bibliography" },

  // Math
  { label: "\\frac", detail: "math", info: "Fraction" },
  { label: "\\sqrt", detail: "math", info: "Square root" },
  { label: "\\sum", detail: "math" },
  { label: "\\prod", detail: "math" },
  { label: "\\int", detail: "math" },
  { label: "\\iint", detail: "math" },
  { label: "\\iiint", detail: "math" },
  { label: "\\oint", detail: "math" },
  { label: "\\lim", detail: "math" },
  { label: "\\sin", detail: "math" },
  { label: "\\cos", detail: "math" },
  { label: "\\tan", detail: "math" },
  { label: "\\log", detail: "math" },
  { label: "\\ln", detail: "math" },
  { label: "\\exp", detail: "math" },
  { label: "\\max", detail: "math" },
  { label: "\\min", detail: "math" },
  { label: "\\inf", detail: "math" },
  { label: "\\sup", detail: "math" },
  { label: "\\det", detail: "math" },
  { label: "\\gcd", detail: "math" },
  { label: "\\binom", detail: "math" },
  { label: "\\mathbb", detail: "math" },
  { label: "\\mathbf", detail: "math" },
  { label: "\\mathit", detail: "math" },
  { label: "\\mathrm", detail: "math" },
  { label: "\\mathsf", detail: "math" },
  { label: "\\mathcal", detail: "math" },
  { label: "\\mathfrak", detail: "math" },
  { label: "\\mathscr", detail: "math" },
  { label: "\\boldsymbol", detail: "math" },
  { label: "\\overline", detail: "math" },
  { label: "\\widehat", detail: "math" },
  { label: "\\widetilde", detail: "math" },
  { label: "\\vec", detail: "math" },
  { label: "\\dot", detail: "math" },
  { label: "\\ddot", detail: "math" },
  { label: "\\hat", detail: "math" },
  { label: "\\tilde", detail: "math" },
  { label: "\\bar", detail: "math" },
  { label: "\\partial", detail: "math" },
  { label: "\\nabla", detail: "math" },
  { label: "\\infty", detail: "math" },
  { label: "\\cdot", detail: "math" },
  { label: "\\cdots", detail: "math" },
  { label: "\\ldots", detail: "math" },
  { label: "\\vdots", detail: "math" },
  { label: "\\ddots", detail: "math" },
  { label: "\\quad", detail: "math" },
  { label: "\\qquad", detail: "math" },
  { label: "\\text", detail: "math", info: "Text mode inside math" },
  { label: "\\operatorname", detail: "math" },
  { label: "\\DeclareMathOperator", detail: "math" },

  // Greek
  { label: "\\alpha", detail: "greek" },
  { label: "\\beta", detail: "greek" },
  { label: "\\gamma", detail: "greek" },
  { label: "\\delta", detail: "greek" },
  { label: "\\epsilon", detail: "greek" },
  { label: "\\varepsilon", detail: "greek" },
  { label: "\\zeta", detail: "greek" },
  { label: "\\eta", detail: "greek" },
  { label: "\\theta", detail: "greek" },
  { label: "\\vartheta", detail: "greek" },
  { label: "\\iota", detail: "greek" },
  { label: "\\kappa", detail: "greek" },
  { label: "\\lambda", detail: "greek" },
  { label: "\\mu", detail: "greek" },
  { label: "\\nu", detail: "greek" },
  { label: "\\xi", detail: "greek" },
  { label: "\\pi", detail: "greek" },
  { label: "\\varpi", detail: "greek" },
  { label: "\\rho", detail: "greek" },
  { label: "\\varrho", detail: "greek" },
  { label: "\\sigma", detail: "greek" },
  { label: "\\varsigma", detail: "greek" },
  { label: "\\tau", detail: "greek" },
  { label: "\\upsilon", detail: "greek" },
  { label: "\\phi", detail: "greek" },
  { label: "\\varphi", detail: "greek" },
  { label: "\\chi", detail: "greek" },
  { label: "\\psi", detail: "greek" },
  { label: "\\omega", detail: "greek" },
  { label: "\\Gamma", detail: "greek" },
  { label: "\\Delta", detail: "greek" },
  { label: "\\Theta", detail: "greek" },
  { label: "\\Lambda", detail: "greek" },
  { label: "\\Xi", detail: "greek" },
  { label: "\\Pi", detail: "greek" },
  { label: "\\Sigma", detail: "greek" },
  { label: "\\Upsilon", detail: "greek" },
  { label: "\\Phi", detail: "greek" },
  { label: "\\Psi", detail: "greek" },
  { label: "\\Omega", detail: "greek" },

  // Math symbols
  { label: "\\leq", detail: "symbol" },
  { label: "\\geq", detail: "symbol" },
  { label: "\\neq", detail: "symbol" },
  { label: "\\approx", detail: "symbol" },
  { label: "\\equiv", detail: "symbol" },
  { label: "\\sim", detail: "symbol" },
  { label: "\\propto", detail: "symbol" },
  { label: "\\in", detail: "symbol" },
  { label: "\\notin", detail: "symbol" },
  { label: "\\subset", detail: "symbol" },
  { label: "\\supset", detail: "symbol" },
  { label: "\\subseteq", detail: "symbol" },
  { label: "\\cup", detail: "symbol" },
  { label: "\\cap", detail: "symbol" },
  { label: "\\emptyset", detail: "symbol" },
  { label: "\\forall", detail: "symbol" },
  { label: "\\exists", detail: "symbol" },
  { label: "\\rightarrow", detail: "symbol" },
  { label: "\\leftarrow", detail: "symbol" },
  { label: "\\Rightarrow", detail: "symbol" },
  { label: "\\Leftarrow", detail: "symbol" },
  { label: "\\Leftrightarrow", detail: "symbol" },
  { label: "\\to", detail: "symbol" },
  { label: "\\mapsto", detail: "symbol" },
  { label: "\\pm", detail: "symbol" },
  { label: "\\mp", detail: "symbol" },
  { label: "\\times", detail: "symbol" },
  { label: "\\div", detail: "symbol" },
  { label: "\\ast", detail: "symbol" },
  { label: "\\star", detail: "symbol" },
  { label: "\\circ", detail: "symbol" },
  { label: "\\bullet", detail: "symbol" },
  { label: "\\oplus", detail: "symbol" },
  { label: "\\otimes", detail: "symbol" },

  // Lists / boxes
  { label: "\\item", detail: "list" },
  { label: "\\noindent", detail: "layout" },
  { label: "\\centering", detail: "layout" },
  { label: "\\newline", detail: "layout" },
  { label: "\\newpage", detail: "layout" },
  { label: "\\clearpage", detail: "layout" },
  { label: "\\pagebreak", detail: "layout" },
  { label: "\\linebreak", detail: "layout" },
  { label: "\\hfill", detail: "layout" },
  { label: "\\vfill", detail: "layout" },
  { label: "\\vspace", detail: "layout" },
  { label: "\\hspace", detail: "layout" },
  { label: "\\smallskip", detail: "layout" },
  { label: "\\medskip", detail: "layout" },
  { label: "\\bigskip", detail: "layout" },

  // Figures / tables
  { label: "\\includegraphics", detail: "graphics", info: "Insert image (graphicx)" },
  { label: "\\caption", detail: "float" },
  { label: "\\subcaption", detail: "float" },
  { label: "\\figure", detail: "float" },
  { label: "\\table", detail: "float" },
  { label: "\\multicolumn", detail: "table" },
  { label: "\\multirow", detail: "table" },
  { label: "\\hline", detail: "table" },
  { label: "\\cline", detail: "table" },
  { label: "\\toprule", detail: "booktabs" },
  { label: "\\midrule", detail: "booktabs" },
  { label: "\\bottomrule", detail: "booktabs" },

  // Macros
  { label: "\\newcommand", detail: "macro" },
  { label: "\\renewcommand", detail: "macro" },
  { label: "\\providecommand", detail: "macro" },
  { label: "\\newenvironment", detail: "macro" },
  { label: "\\renewenvironment", detail: "macro" },
  { label: "\\def", detail: "macro" },
  { label: "\\let", detail: "macro" },
  { label: "\\input", detail: "io" },
  { label: "\\include", detail: "io" },
  { label: "\\InputIfFileExists", detail: "io" },

  // Hyperlinks
  { label: "\\url", detail: "hyperref" },
  { label: "\\href", detail: "hyperref" },
  { label: "\\hypersetup", detail: "hyperref" },

  // Misc
  { label: "\\footnote", detail: "note" },
  { label: "\\marginpar", detail: "note" },
  { label: "\\today", detail: "misc" },
  { label: "\\LaTeX", detail: "misc" },
  { label: "\\TeX", detail: "misc" },

  // Environment names suggested when typing \begin{
  // These are handled separately as ENV_NAMES below.
];

export const ENV_NAMES: string[] = [
  "document",
  "abstract",
  "equation",
  "equation*",
  "align",
  "align*",
  "gather",
  "gather*",
  "multline",
  "multline*",
  "split",
  "cases",
  "matrix",
  "pmatrix",
  "bmatrix",
  "Bmatrix",
  "vmatrix",
  "Vmatrix",
  "array",
  "itemize",
  "enumerate",
  "description",
  "figure",
  "figure*",
  "table",
  "table*",
  "tabular",
  "tabularx",
  "tabular*",
  "longtable",
  "center",
  "flushleft",
  "flushright",
  "quote",
  "quotation",
  "verse",
  "verbatim",
  "verbatim*",
  "lstlisting",
  "minted",
  "proof",
  "theorem",
  "lemma",
  "corollary",
  "proposition",
  "definition",
  "remark",
  "example",
  "tikzpicture",
  "scope",
  "axis",
  "frame",
  "block",
  "alertblock",
  "exampleblock",
  "columns",
  "column",
];
